version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: quizonline
      MYSQL_USER: root3
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"

  quiz-backend:
    build:
      context: ./quizBckend-Online
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    ports:
      - "9080:9090"
    image: i0xnaveen/quiz-backend:latest 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/quizonline
      SPRING_DATASOURCE_USERNAME: root3
      SPRING_DATASOURCE_PASSWORD: mysql
